-- Complete Supabase Setup for Hausa Wedding Guide
-- Run this SQL in your Supabase SQL editor

-- 1. Drop existing table if it exists (clean slate)
DROP TABLE IF EXISTS public.sales CASCADE;

-- 2. Create sales table
CREATE TABLE public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tx_ref TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    file_name TEXT NOT NULL DEFAULT 'Hausa_Wedding_Guide.pdf',
    downloads INTEGER NOT NULL DEFAULT 0,
    max_downloads INTEGER NOT NULL DEFAULT 3,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Create indexes for performance
CREATE INDEX idx_sales_email ON public.sales(email);
CREATE INDEX idx_sales_tx_ref ON public.sales(tx_ref);
CREATE INDEX idx_sales_created_at ON public.sales(created_at);

-- 4. Enable Row Level Security
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

-- 5. Create policies for service role access
-- This allows our API (using service role key) to read/write
CREATE POLICY "Service role can do everything" ON public.sales
FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

-- 6. Create policy for authenticated users (if needed later)
CREATE POLICY "Users can read their own sales" ON public.sales
FOR SELECT USING (auth.uid()::text = email);

-- 7. Grant necessary permissions
GRANT ALL ON public.sales TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.sales_id_seq TO service_role;
