-- Create sales table for Hausa Wedding Guide
-- Run this SQL in your Supabase SQL editor

CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tx_ref TEXT NOT NULL,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    file_name TEXT NOT NULL DEFAULT 'Hausa_Wedding_Guide.pdf',
    downloads INTEGER NOT NULL DEFAULT 0,
    max_downloads INTEGER NOT NULL DEFAULT 3,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for faster email lookups
CREATE INDEX IF NOT EXISTS idx_sales_email ON public.sales(email);
CREATE INDEX IF NOT EXISTS idx_sales_tx_ref ON public.sales(tx_ref);

-- Add Row Level Security (optional)
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
